### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yukisan04** [yukisan04/furima-41486#21]
# 自身のフリマアプリのURL
・https://furima-41486.onrender.com/
# Basic認証のIDとパスワード
・ID    :  admin
・pass:  1234
# 出品者用のメールアドレスとパスワード
・メールアドレス：sample@sample.com
・パスワード　　：Sample1
# 購入者用のメールアドレスとパスワード
・メールアドレス：sample2@sample.com
・パスワード　　：Sample2
# 購入用カードの番号・期限・セキュリティコード
・番号：4242424242424242
・期限：12/23
・セキュリティコード：123

**Comment by motomuun** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
商品出品機能の確認

- [x] **販売手数料と利益の合計が、販売価格と一致しません。一致するように修正をお願いします。**
<img width="669" alt="スクリーンショット 2024-10-22 9 13 54" src="https://github.com/user-attachments/assets/49f18df3-397e-4694-8514-b227a49f2408">

- [x] **各プルダウンの1つめの要素が「--」になってます。実装要件だと「---」です。
細かい点ですが実装要件と揃えるために「---」に修正をお願いします。**
<img width="681" alt="スクリーンショット 2024-10-22 9 15 22" src="https://github.com/user-attachments/assets/4eff87e6-4963-4b11-8b2d-868045f23159">

- [x] **プルダウン「商品の状態」の「新品、未使用」ですが、実装要件では「新品・未使用」です。こちらも細かい点ですが、要件と揃えるために「新品・未使用」に修正をお願いします。**
<img width="330" alt="スクリーンショット 2024-10-22 9 16 54" src="https://github.com/user-attachments/assets/9257065a-4f90-457c-8ec5-67d5aa84c458">


**商品編集機能の確認**

- [x] **編集ページの見た目において、出品ページと異なる部分があります。「発送元の地域」以外のプルダウンの見た目が、出品ページと同じになるように修正をお願いします。**
<img width="683" alt="スクリーンショット 2024-10-22 9 19 39" src="https://github.com/user-attachments/assets/ed7a2bcd-9ad4-40cc-ba38-d8ad2aaf13d4">


**商品購入機能の確認**

- [x] **購入ページにおいて、クレジットカードの情報を入力するフォームにカーソルをあわせても入力状態にならず、入力出来ません。入力出来るように修正をお願いします。**

※購入後の機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。
修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yukisan04** [comment]
修正完了いたしました。ご確認お願い致します。

**Comment by yuri240** [comment]
最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
